### ISSUE TITLE
Добавить размеры деталей

### ISSUE THREAD

**Issue by Zener085** [iluha23/Snake-game#6]
Добавить константу - размеры блока (квадрата) поля игры, желательно, чтобы в экран вмещалось целое кол-во квадратных полей

Добавить параметр змее - размер - он будет обозначать размеры змеи, параметр должен быть равен одному блоку поля

**Comment by Zener085** [comment]
Это задание нужно выполнить после задания с проверкой pull request

**Comment by iluha23** [comment]
Добавить константу - размеры блока (квадрата) поля игры, желательно, чтобы в экран вмещалось целое кол-во квадратных полей
два вопроса
какие размеры блока бывают?
и
что за квадратные поля
которые должны там помещаться
привет кстати

**Comment by Zener085** [comment]
1) Размеры любые, от 1 пикселя до полного окна, отмечай, желательно выделить на 1 квадрат то число, которое является делителем для длины и ширины окна (чтобы в окне помещалось четно кол-во блоков)

2) квадратные поля или блоки - ячейки на игровом поле, которое может быть заполнено игровым предметом (1 блок змеи или же еда) или быть пустым в зависимости от ситуации.

3) Не копируй свой текст из других источников, либо спрашивай в одном месте (тут ИЛИ в дискорде), либо задавай вопросы корректно - повторять строку, которая находится на 5 сантиметров выше, а также писать тут "кстати привет" абсолютно бесполезно
